[package]
name = "lis"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
bytes = "1.7.1"
clap = { version = "4.5.13", features = ["derive"] }
futures-lite = "2.3.0"
iroh = "0.22.0"
serde = "1.0.205"
serde_json = "1.0.122"
tempfile = "3.12.0"
tokio = "1.39.2"
