[package]
name = "lis"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.13", features = ["derive"] }
futures-lite = "2.3.0"
iroh = "0.22.0"
tokio = "1.39.2"
